### ISSUE TITLE
OSM Connector - Missing Javascript

### ISSUE THREAD

**Issue by teddy-rachmayadi** [Andyeyo/Odoo-Addons#2]
There is no javascript library in static folder /osm_connector/static/src/js/lib

**Comment by bartacruz** [comment]
Same here. Please upload the files. I was trying to port the module to Odoo 15.0

**Comment by Andyeyo** [comment]
> Same here. Please upload the files. I was trying to port the module to Odoo 15.0

I will migrate to Odoo 15.0
